wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.7
    cli_version: 0.17.8
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1725409724
    t:
      1:
      - 55
      - 105
      2:
      - 55
      - 105
      3:
      - 23
      4: 3.11.7
      5: 0.17.8
      8:
      - 5
      13: linux-x86_64
