# name: str
#     model_name: str
#     endpoints: default to null
#         - api_base: str
#           api_key: str
#           api_version: str optional (only for azure)
#     api_type: str
#     tokenizer: str optional (to optimize token limits)
#     parallel: int
#     system_prompt: str optional (add system instruction when generating model answer)

Qwen2.5-1B-DPO-npu0.05:
    model_name: Qwen2.5-1B-DPO-npu0.05
    endpoints:
        api_base: "http://localhost:8000"
        api_key: "EMPTY"
    api_type: openai
    parallel: 1

gpt-3.5-turbo-0125:
    model_name: gpt-3.5-turbo-0125
    endpoints: null
    api_type: openai
    parallel: 8

gpt-4-0314:
    model_name: gpt-4-0314
    endpoints: null
    api_type: openai
    parallel: 8

gpt-4-1106-preview:
    model_name: gpt-4-1106-preview
    endpoints: null
    api_type: openai
    parallel: 8

deepseek-chat:
    model_name: deepseek-chat
    endpoints:
        api_base: "https://api.deepseek.com/v1"
        api_key: "sk-939897bcd73244488114250043c8d36b"
    api_type: openai
    parallel: 8

